// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/service/google_sheets/main.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sheets "google.golang.org/api/sheets/v4"
)

// MockGoogleSheetsRepository is a mock of GoogleSheetsRepository interface.
type MockGoogleSheetsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleSheetsRepositoryMockRecorder
}

// MockGoogleSheetsRepositoryMockRecorder is the mock recorder for MockGoogleSheetsRepository.
type MockGoogleSheetsRepositoryMockRecorder struct {
	mock *MockGoogleSheetsRepository
}

// NewMockGoogleSheetsRepository creates a new mock instance.
func NewMockGoogleSheetsRepository(ctrl *gomock.Controller) *MockGoogleSheetsRepository {
	mock := &MockGoogleSheetsRepository{ctrl: ctrl}
	mock.recorder = &MockGoogleSheetsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleSheetsRepository) EXPECT() *MockGoogleSheetsRepositoryMockRecorder {
	return m.recorder
}

// BatchUpdate mocks base method.
func (m *MockGoogleSheetsRepository) BatchUpdate(req *sheets.BatchUpdateSpreadsheetRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockGoogleSheetsRepositoryMockRecorder) BatchUpdate(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockGoogleSheetsRepository)(nil).BatchUpdate), req)
}

// GetSheetID mocks base method.
func (m *MockGoogleSheetsRepository) GetSheetID() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSheetID")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSheetID indicates an expected call of GetSheetID.
func (mr *MockGoogleSheetsRepositoryMockRecorder) GetSheetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSheetID", reflect.TypeOf((*MockGoogleSheetsRepository)(nil).GetSheetID))
}
